flip -u mnru\calc-snr.c
flip -u mnru\mnru.c
flip -u mnru\mnru.h
flip -u mnru\mnrudemo.c
flip -u mnru\snr.c
flip -u mnru\make-vms.com
flip -u mnru\makefile.djc
flip -u mnru\makefile.tcc
flip -u mnru\makefile.unx
flip -u mnru\mnru.rme
flip -u mnru\makefile.cl
flip -u maketcc.bat
flip -u g726\cvt_h_b.c
flip -u g726\g726.c
flip -u g726\g726.h
flip -u g726\g726.rme
flip -u g726\g726demo.c
flip -u g726\make-vms.com
flip -u g726\makefile.cl
flip -u g726\makefile.djc
flip -u g726\makefile.unx
flip -u g726\vbr-g726.c
flip -u g726\makefile.tcc
flip -u iir\c712demo.c
flip -u iir\cascg712.c
flip -u iir\cirsdemo.c
flip -u iir\iir-g712.c
flip -u iir\iir-irs.c
flip -u iir\iir-lib.c
flip -u iir\iir.rme
flip -u iir\iirflt.c
flip -u iir\iirflt.h
flip -u iir\makefile.unx
flip -u iir\pcmdemo.c
flip -u iir\makefile.djc
flip -u iir\makefile.tcc
flip -u iir\iir-dir.c
flip -u iir\iir-flat.c
flip -u iir\makefile.cl
flip -u is54\bin\make-vms.com
flip -u is54\bin\makefile.djc
flip -u is54\bin\makefile.unx
flip -u is54\bin\makefile.cl
flip -u is54\bin\makefile.tcc
flip -u is54\b_con.c
flip -u is54\calcp.c
flip -u is54\cunpack0.c
flip -u is54\decorr.c
flip -u is54\excite.c
flip -u is54\filt4.c
flip -u is54\filters.c
flip -u is54\flatv.c
flip -u is54\fspace.c
flip -u is54\g_quant.c
flip -u is54\getp.c
flip -u is54\init.c
flip -u is54\interp.c
flip -u is54\is54.rme
flip -u is54\lag.c
flip -u is54\make-vms.com
flip -u is54\makec.c
flip -u is54\makefile.cl
flip -u is54\makefile.djc
flip -u is54\makefile.unx
flip -u is54\p_ex.c
flip -u is54\pconv.c
flip -u is54\putc.c
flip -u is54\r_sub.c
flip -u is54\r_sub.h
flip -u is54\rs_rr.c
flip -u is54\t_sub.c
flip -u is54\t_sub.h
flip -u is54\v_con.c
flip -u is54\v_srch.c
flip -u is54\vparams.h
flip -u is54\vselp.c
flip -u is54\vselp.h
flip -u is54\wsnr.c
flip -u is54\mysplit.c
flip -u is54\makefile.tcc
flip -u rpeltp\add.c
flip -u rpeltp\add_test.c
flip -u rpeltp\code.c
flip -u rpeltp\config.h
flip -u rpeltp\debug.c
flip -u rpeltp\decode.c
flip -u rpeltp\gsm.h
flip -u rpeltp\gsm_crea.c
flip -u rpeltp\gsm_deco.c
flip -u rpeltp\gsm_dest.c
flip -u rpeltp\gsm_enco.c
flip -u rpeltp\gsm_expl.c
flip -u rpeltp\gsm_impl.c
flip -u rpeltp\gsm_opti.c
flip -u rpeltp\gsm_prin.c
flip -u rpeltp\long_ter.c
flip -u rpeltp\lpc.c
flip -u rpeltp\make-vms.com
flip -u rpeltp\makefile.tcc
flip -u rpeltp\makefile.unx
flip -u rpeltp\preproce.c
flip -u rpeltp\private.h
flip -u rpeltp\proto.h
flip -u rpeltp\rpe.c
flip -u rpeltp\rpedemo.c
flip -u rpeltp\rpeltp.c
flip -u rpeltp\rpeltp.h
flip -u rpeltp\rpeltp.rme
flip -u rpeltp\short_te.c
flip -u rpeltp\table.c
flip -u rpeltp\unproto.h
flip -u rpeltp\makefile.djc
flip -u rpeltp\ts\makefile.djc
flip -u rpeltp\ts\makefile.unx
flip -u rpeltp\ts\make-vms.com
flip -u rpeltp\ts\makefile.cl
flip -u rpeltp\ts\makefile.tcc
flip -u rpeltp\makefile.cl
flip -u fir\filter.c
flip -u fir\fir-dsm.c
flip -u fir\fir-flat.c
flip -u fir\fir-hirs.c
flip -u fir\fir-irs.c
flip -u fir\fir-lib.c
flip -u fir\fir-pso.c
flip -u fir\fir-tia.c
flip -u fir\fir.rme
flip -u fir\firdemo.c
flip -u fir\firflt.c
flip -u fir\firflt.h
flip -u fir\fltresp.c
flip -u fir\make-vms.com
flip -u fir\makefile.cl
flip -u fir\makefile.djc
flip -u fir\makefile.unx
flip -u fir\makefile.tcc
flip -u fir\fir-wb.c
flip -u fir\fir-msin.c
flip -u fir\test-fir.rme
flip -u utl\ugstdemo.h
flip -u utl\makefile.unx
flip -u utl\spdemo.c
flip -u utl\ugst-utl.c
flip -u utl\ugst-utl.h
flip -u utl\ugst-utl.rme
flip -u utl\makefile.djc
flip -u utl\makefile.tcc
flip -u utl\scaldemo.c
flip -u utl\makefile.cl
flip -u unsup\pshar\make-vms.com
flip -u unsup\pshar\makefile.djc
flip -u unsup\pshar\makefile.unx
flip -u unsup\pshar\pshar.c
flip -u unsup\pshar\pshar.rme
flip -u unsup\pshar\makefile.tcc
flip -u unsup\compfile.c
flip -u unsup\dumpfile.c
flip -u unsup\measure.c
flip -u unsup\sb.c
flip -u unsup\sub-add.c
flip -u unsup\sine.c
flip -u unsup\xencode.c
flip -u unsup\fdelay.c
flip -u unsup\xdecode.c
flip -u unsup\makefile.unx
flip -u unsup\unsupp.rme
flip -u unsup\rm.bat
flip -u unsup\g728-vt\cwcomp.c
flip -u unsup\g728-vt\filsub.c
flip -u unsup\g728-vt\ldcdec.c
flip -u unsup\g728-vt\ldcsub.c
flip -u unsup\g728-vt\makefile
flip -u unsup\g728-vt\s_rnge.c
flip -u unsup\g728-vt\sig_die.c
flip -u unsup\g728-vt\snr.c
flip -u unsup\g728-vt\wsnr.c
flip -u unsup\oper.c
flip -u unsup\sh2chr.c
flip -u unsup\chr2sh.c
flip -u unsup\makefile.sun
flip -u unsup\endian.c
flip -u unsup\swapover.bat
flip -u unsup\asc2bin.c
flip -u unsup\concat.c
flip -u unsup\makefile.djc
flip -u unsup\sig-snr.h
flip -u unsup\makefile.cl
flip -u unsup\bin2asc.c
flip -u unsup\makefile.tcc
flip -u unsup\sb-ori.c
flip -u unsup\astrip.c
flip -u unsup\getcrc32.c
flip -u g711\g711.c
flip -u g711\g711.h
flip -u g711\g711.rme
flip -u g711\g711demo.c
flip -u g711\shiftbit.c
flip -u g711\makefile.unx
flip -u g711\makefile.tcc
flip -u g711\makefile.cl
flip -u g711\makefile.djc
flip -u sv56\actlevel.c
flip -u sv56\makefile.unx
flip -u sv56\sv-p56.c
flip -u sv56\sv-p56.h
flip -u sv56\sv-p56.rme
flip -u sv56\sv56demo.c
flip -u sv56\makefile.djc
flip -u sv56\makefile.tcc
flip -u sv56\makefile.cl
flip -u test-zip.bat
flip -u g722\makefile.unx
flip -u g722\decg722.c
flip -u g722\encg722.c
flip -u g722\funcg722.c
flip -u g722\funcg722.h
flip -u g722\g722.c
flip -u g722\g722.h
flip -u g722\g722.rme
flip -u g722\g722demo.c
flip -u g722\makefile.djc
flip -u g722\makefile.tcc
flip -u g722\operg722.c
flip -u g722\operg722.h
flip -u g722\tstcg722.c
flip -u g722\tstdg722.c
flip -u g722\makefile.cl
flip -u flip-dos.bat
flip -u gccmk.bat
flip -u makedjc.bat
flip -u tccmk.bat
flip -u makefile.unx
flip -u eid\eid.rme
flip -u eid\eid.c
flip -u eid\eid.h
flip -u eid\eid8k.c
flip -u eid\eid_io.c
flip -u eid\eid_io.h
flip -u eid\eiddemo.c
flip -u eid\make-vms.com
flip -u eid\makefile.cl
flip -u eid\makefile.djc
flip -u eid\makefile.unx
flip -u eid\ep-stats.c
flip -u eid\softbit.c
flip -u eid\eid-xor.c
flip -u eid\gen-patt.c
flip -u eid\eid-int.c
flip -u eid\cvt-head.c
flip -u eid\softbit.h
flip -u eid\dec-patt.c
flip -u eid\makefile.tcc
flip -u eid\zero-eid.rme
flip -u stl2000.rme
flip -u g727\g727.rme
flip -u g727\discard.c
flip -u g727\g727-tv.rme
flip -u g727\g727demo.c
flip -u g727\makefile.djc
flip -u g727\g727.c
flip -u g727\g727.h
flip -u g727\makefile.cl
flip -u g727\makefile.unx
flip -u g727\makefile.tcc
flip -u basop\count.c
flip -u basop\typedef.h
flip -u basop\basop32.c
flip -u basop\basop32.h
flip -u basop\basop.rme
flip -u basop\count.h
flip -u flip-unx.bat
flip -u makecl.bat
flip -u clmk.bat
