flip -m mnru\calc-snr.c
flip -m mnru\mnru.c
flip -m mnru\mnru.h
flip -m mnru\mnrudemo.c
flip -m mnru\snr.c
flip -m mnru\make-vms.com
flip -m mnru\makefile.djc
flip -m mnru\makefile.tcc
flip -m mnru\makefile.unx
flip -m mnru\mnru.rme
flip -m mnru\makefile.cl
flip -m maketcc.bat
flip -m g726\cvt_h_b.c
flip -m g726\g726.c
flip -m g726\g726.h
flip -m g726\g726.rme
flip -m g726\g726demo.c
flip -m g726\make-vms.com
flip -m g726\makefile.cl
flip -m g726\makefile.djc
flip -m g726\makefile.unx
flip -m g726\vbr-g726.c
flip -m g726\makefile.tcc
flip -m iir\c712demo.c
flip -m iir\cascg712.c
flip -m iir\cirsdemo.c
flip -m iir\iir-g712.c
flip -m iir\iir-irs.c
flip -m iir\iir-lib.c
flip -m iir\iir.rme
flip -m iir\iirflt.c
flip -m iir\iirflt.h
flip -m iir\makefile.unx
flip -m iir\pcmdemo.c
flip -m iir\makefile.djc
flip -m iir\makefile.tcc
flip -m iir\iir-dir.c
flip -m iir\iir-flat.c
flip -m iir\makefile.cl
flip -m is54\bin\make-vms.com
flip -m is54\bin\makefile.djc
flip -m is54\bin\makefile.unx
flip -m is54\bin\makefile.cl
flip -m is54\bin\makefile.tcc
flip -m is54\b_con.c
flip -m is54\calcp.c
flip -m is54\cunpack0.c
flip -m is54\decorr.c
flip -m is54\excite.c
flip -m is54\filt4.c
flip -m is54\filters.c
flip -m is54\flatv.c
flip -m is54\fspace.c
flip -m is54\g_quant.c
flip -m is54\getp.c
flip -m is54\init.c
flip -m is54\interp.c
flip -m is54\is54.rme
flip -m is54\lag.c
flip -m is54\make-vms.com
flip -m is54\makec.c
flip -m is54\makefile.cl
flip -m is54\makefile.djc
flip -m is54\makefile.unx
flip -m is54\p_ex.c
flip -m is54\pconv.c
flip -m is54\putc.c
flip -m is54\r_sub.c
flip -m is54\r_sub.h
flip -m is54\rs_rr.c
flip -m is54\t_sub.c
flip -m is54\t_sub.h
flip -m is54\v_con.c
flip -m is54\v_srch.c
flip -m is54\vparams.h
flip -m is54\vselp.c
flip -m is54\vselp.h
flip -m is54\wsnr.c
flip -m is54\mysplit.c
flip -m is54\makefile.tcc
flip -m rpeltp\add.c
flip -m rpeltp\add_test.c
flip -m rpeltp\code.c
flip -m rpeltp\config.h
flip -m rpeltp\debug.c
flip -m rpeltp\decode.c
flip -m rpeltp\gsm.h
flip -m rpeltp\gsm_crea.c
flip -m rpeltp\gsm_deco.c
flip -m rpeltp\gsm_dest.c
flip -m rpeltp\gsm_enco.c
flip -m rpeltp\gsm_expl.c
flip -m rpeltp\gsm_impl.c
flip -m rpeltp\gsm_opti.c
flip -m rpeltp\gsm_prin.c
flip -m rpeltp\long_ter.c
flip -m rpeltp\lpc.c
flip -m rpeltp\make-vms.com
flip -m rpeltp\makefile.tcc
flip -m rpeltp\makefile.unx
flip -m rpeltp\preproce.c
flip -m rpeltp\private.h
flip -m rpeltp\proto.h
flip -m rpeltp\rpe.c
flip -m rpeltp\rpedemo.c
flip -m rpeltp\rpeltp.c
flip -m rpeltp\rpeltp.h
flip -m rpeltp\rpeltp.rme
flip -m rpeltp\short_te.c
flip -m rpeltp\table.c
flip -m rpeltp\unproto.h
flip -m rpeltp\makefile.djc
flip -m rpeltp\ts\makefile.djc
flip -m rpeltp\ts\makefile.unx
flip -m rpeltp\ts\make-vms.com
flip -m rpeltp\ts\makefile.cl
flip -m rpeltp\ts\makefile.tcc
flip -m rpeltp\makefile.cl
flip -m fir\filter.c
flip -m fir\fir-dsm.c
flip -m fir\fir-flat.c
flip -m fir\fir-hirs.c
flip -m fir\fir-irs.c
flip -m fir\fir-lib.c
flip -m fir\fir-pso.c
flip -m fir\fir-tia.c
flip -m fir\fir.rme
flip -m fir\firdemo.c
flip -m fir\firflt.c
flip -m fir\firflt.h
flip -m fir\fltresp.c
flip -m fir\make-vms.com
flip -m fir\makefile.cl
flip -m fir\makefile.djc
flip -m fir\makefile.unx
flip -m fir\makefile.tcc
flip -m fir\fir-wb.c
flip -m fir\fir-msin.c
flip -m fir\test-fir.rme
flip -m utl\ugstdemo.h
flip -m utl\makefile.unx
flip -m utl\spdemo.c
flip -m utl\ugst-utl.c
flip -m utl\ugst-utl.h
flip -m utl\ugst-utl.rme
flip -m utl\makefile.djc
flip -m utl\makefile.tcc
flip -m utl\scaldemo.c
flip -m utl\makefile.cl
flip -m unsup\pshar\make-vms.com
flip -m unsup\pshar\makefile.djc
flip -m unsup\pshar\makefile.unx
flip -m unsup\pshar\pshar.c
flip -m unsup\pshar\pshar.rme
flip -m unsup\pshar\makefile.tcc
flip -m unsup\compfile.c
flip -m unsup\dumpfile.c
flip -m unsup\measure.c
flip -m unsup\sb.c
flip -m unsup\sub-add.c
flip -m unsup\sine.c
flip -m unsup\xencode.c
flip -m unsup\fdelay.c
flip -m unsup\xdecode.c
flip -m unsup\makefile.unx
flip -m unsup\unsupp.rme
flip -m unsup\rm.bat
flip -m unsup\g728-vt\cwcomp.c
flip -m unsup\g728-vt\filsub.c
flip -m unsup\g728-vt\ldcdec.c
flip -m unsup\g728-vt\ldcsub.c
flip -m unsup\g728-vt\makefile
flip -m unsup\g728-vt\s_rnge.c
flip -m unsup\g728-vt\sig_die.c
flip -m unsup\g728-vt\snr.c
flip -m unsup\g728-vt\wsnr.c
flip -m unsup\oper.c
flip -m unsup\sh2chr.c
flip -m unsup\chr2sh.c
flip -m unsup\makefile.sun
flip -m unsup\endian.c
flip -m unsup\swapover.bat
flip -m unsup\asc2bin.c
flip -m unsup\concat.c
flip -m unsup\makefile.djc
flip -m unsup\sig-snr.h
flip -m unsup\makefile.cl
flip -m unsup\bin2asc.c
flip -m unsup\makefile.tcc
flip -m unsup\sb-ori.c
flip -m unsup\astrip.c
flip -m unsup\getcrc32.c
flip -m g711\g711.c
flip -m g711\g711.h
flip -m g711\g711.rme
flip -m g711\g711demo.c
flip -m g711\shiftbit.c
flip -m g711\makefile.unx
flip -m g711\makefile.tcc
flip -m g711\makefile.cl
flip -m g711\makefile.djc
flip -m sv56\actlevel.c
flip -m sv56\makefile.unx
flip -m sv56\sv-p56.c
flip -m sv56\sv-p56.h
flip -m sv56\sv-p56.rme
flip -m sv56\sv56demo.c
flip -m sv56\makefile.djc
flip -m sv56\makefile.tcc
flip -m sv56\makefile.cl
flip -m test-zip.bat
flip -m g722\makefile.unx
flip -m g722\decg722.c
flip -m g722\encg722.c
flip -m g722\funcg722.c
flip -m g722\funcg722.h
flip -m g722\g722.c
flip -m g722\g722.h
flip -m g722\g722.rme
flip -m g722\g722demo.c
flip -m g722\makefile.djc
flip -m g722\makefile.tcc
flip -m g722\operg722.c
flip -m g722\operg722.h
flip -m g722\tstcg722.c
flip -m g722\tstdg722.c
flip -m g722\makefile.cl
flip -m flip-dos.bat
flip -m gccmk.bat
flip -m makedjc.bat
flip -m tccmk.bat
flip -m makefile.unx
flip -m eid\eid.rme
flip -m eid\eid.c
flip -m eid\eid.h
flip -m eid\eid8k.c
flip -m eid\eid_io.c
flip -m eid\eid_io.h
flip -m eid\eiddemo.c
flip -m eid\make-vms.com
flip -m eid\makefile.cl
flip -m eid\makefile.djc
flip -m eid\makefile.unx
flip -m eid\ep-stats.c
flip -m eid\softbit.c
flip -m eid\eid-xor.c
flip -m eid\gen-patt.c
flip -m eid\eid-int.c
flip -m eid\cvt-head.c
flip -m eid\softbit.h
flip -m eid\dec-patt.c
flip -m eid\makefile.tcc
flip -m eid\zero-eid.rme
flip -m stl2000.rme
flip -m g727\g727.rme
flip -m g727\discard.c
flip -m g727\g727-tv.rme
flip -m g727\g727demo.c
flip -m g727\makefile.djc
flip -m g727\g727.c
flip -m g727\g727.h
flip -m g727\makefile.cl
flip -m g727\makefile.unx
flip -m g727\makefile.tcc
flip -m basop\count.c
flip -m basop\typedef.h
flip -m basop\basop32.c
flip -m basop\basop32.h
flip -m basop\basop.rme
flip -m basop\count.h
flip -m flip-unx.bat
flip -m makecl.bat
flip -m clmk.bat

