# -----------------------------------------------------------------------------
# Unix makefile for compiling and testing the 
# UGST P.56 speech voltmeter.
# Executable must be defined by SVP56 and ACTLEV below.
#
# Implemented by <simao@ctd.comsat.com> -- 01.Dec.94
# -----------------------------------------------------------------------------

# ------------------------------------------------
# Choose a file comparison utility: 
# ------------------------------------------------
DIFF = cf -q

# ------------------------------------------------
# Choose an archiving utility: 
#	- public domain unzip, or [PC/Unix/VMS]
#	- shareware pkunzip [PC only]
# ------------------------------------------------
#UNZIP = -pkunzip
UNZIP = unzip -o

# ------------------------------------------------
# Choose compiler & options
# ------------------------------------------------
CC_OPT = -I../utl -g -Wall

# ------------------------------------------------
# General purpose symbols
# ------------------------------------------------
#RM = rm -f
SVP56 = ./sv56demo
ACTLEV = ./actlev
P56_OBJ = sv-p56.o ugst-utl.o

#------------------------------------------------------------------
# Implicit rules
#------------------------------------------------------------------
.c.o:
	$(CC) $(CC_OPT) -c $<

#------------------------------------------------------------------
# Targets and general rules
#------------------------------------------------------------------
all:: sv56demo actlev

anyway: clean all

clean:
	$(RM) *.o

cleantest:
	$(RM) voice.nrm voice.ltl voice.prc voice.rms voice.src

veryclean: clean cleantest
	$(RM) $(SVP56) $(ACTLEV)

#------------------------------------------------------------------
# Specific rules
#------------------------------------------------------------------
sv56demo: sv56demo.o $(P56_OBJ)
	$(CC) $(CC_OPT) -o sv56demo sv56demo.o $(P56_OBJ) -lm

actlev:	actlevel.o $(P56_OBJ)
	$(CC) $(CC_OPT) -o actlev actlevel.o $(P56_OBJ) -lm

ugst-utl.o: ../utl/ugst-utl.c
	$(CC) $(CC_OPT) -c ../utl/ugst-utl.c

#------------------------------------------------------------------
# Test the implementation
# Note: there are no compliance test vectors associated with this module
#------------------------------------------------------------------
test:	proc comp

proc:   voice.src voice.nrm
	# Process by the speech voltmeter, normalize using active level
	$(SVP56) -q voice.src voice.prc 256 1 0 -30
	# Process by the speech voltmeter, normalize using long-term RMS level
	$(SVP56) -q -rms voice.src voice.rms 256 1 0 -30
	# Measure the new file
	$(ACTLEV) -q voice.src voice.nrm voice.prc voice.ltl voice.rms

comp:
	# Compare with reference - no differences should be found.
	$(DIFF) voice.nrm voice.prc
	$(DIFF) voice.ltl voice.rms

#---------------------------------
# Unpack if necessary for testing 
#---------------------------------
voice.nrm:
	$(UNZIP) sv56-tst.zip voice.nrm voice.ltl
	swapover -if little voice.nrm voice.ltl

voice.src: ../is54/bin/is54-tst.zip
	$(UNZIP) ../is54/bin/is54-tst.zip voice.src 
	swapover -if little voice.src
